# -*- coding: utf-8 -*-
"""Divyansh_TARF_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1colW6bcqXd4OJQDefIFy-Wc1_RXDFpgc
"""

import asyncio
from playwright.async_api import async_playwright

async def fetch_case_data_async(case_type, case_number, filing_year):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        try:
            await page.goto("https://services.ecourts.gov.in/ecourtindia_v6/")

            await page.click("text=Case Status")
            await page.click("text=Search by Case Number")

            await page.select_option("#case_type", case_type)
            await page.fill("#case_number", case_number)
            await page.fill("#case_year", filing_year)
            await page.click("input[type='submit']")

            await page.wait_for_load_state("networkidle")
            content = await page.content()

            # These are dummy selectors – you'll likely need to inspect and fix them
            parties = await page.locator("text=Petitioner").all_inner_texts()
            dates = await page.locator("text=Next Hearing Date").all_inner_texts()
            pdf_elem = await page.locator("a[href$='.pdf']").first
            pdf_link = await pdf_elem.get_attribute('href') if await pdf_elem.count() > 0 else None

            return {
                "parties": parties,
                "dates": dates,
                "pdf": pdf_link,
                "raw_html": content,
                "error": None
            }

        except Exception as e:
            return {"error": str(e), "parties": [], "dates": [], "pdf": None, "raw_html": ""}
        finally:
            await browser.close()

def on_submit(b):
    with output_area:
        clear_output()
        ct = case_type_input.value
        cn = case_number_input.value
        year = filing_year_input.value
        print(f"Fetching: {ct}/{cn}/{year}")

        result = asyncio.run(fetch_case_data_async(ct, cn, year))
        log_query(ct, cn, year, result['raw_html'])

        if result['error']:
            print("Error:", result['error'])
        else:
            print("Parties:", result['parties'])
            print("Dates:", result['dates'])
            if result['pdf']:
                display(HTML(f"<a href='{result['pdf']}' target='_blank'>Download PDF</a>"))
            else:
                print("No PDF found.")